language: node_js
node_js: 10

env:
    global:
        - GITHUB_REPO: blckchnd/rudex-balances
install:
    - npm ci
script:
    - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
